
<?php
	session_start();
	session_destroy();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
	<link rel="stylesheet" href="css/reglas.css" type="text/css"/> 
	<title>logout</title>
	
</head>
<body>
	<h1>Sesi&oacute;n terminada</h1>
	
	<div align="center">
		<img src="imagenes/end.jpg" alt="Pau" height="400" width="500" /> <br/>
		<a href="login.php"> P&aacute;gina de Inicio</a> <br/>
	</div>
	
</body>
</html>